### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1410677474** [ascendedguard/LethalCompany.ScrapLossBalancer#1]
When there are more than four people, someone comes in and makes everyone black

**Comment by 1410677474** [comment]
I like this module a lot, but it doesn't work reliably

**Comment by 1410677474** [comment]
probably because latecompany and morecompany

**Comment by ascendedguard** [comment]
> When there are more than four people, someone comes in and makes everyone black

Hmm, it shouldn't be possible for this to be impacting players on join, just because the only time this mod runs any code is after a day ends, with changes only happening on a full team death. I know it doesn't impact Late Company as we use that daily. I can double check against More Company but I have used that previously too.

* When you say it makes everyone black, do you mean player models or something else?
* Is this only happening for the host, or happening for everyone? (The mod only runs for the host, it doesn't run anything for clients)
* Do you have a full mod list of what you have installed?

**Comment by 1410677474** [comment]
>
It doesn't affect people who just joined
> 
All of us installed it
>
I will test it again tomorrow because I haven't used it in a long time and give you feedback

**Comment by 1410677474** [comment]
Thanks for your reply. I will try again tomorrow. It really bothered me before

**Comment by 1410677474** [comment]
I use is TotalPercent

**Comment by ascendedguard** [comment]
Closing. I wasn't able to reproduce after testing a few different ways, and haven't heard of any issues from others. Feel free to post if you're able to determine if it's a compatibility issue with another specific mod.

**Comment by 1410677474** [comment]
ok，I've been playing for a month, and there should be no problem.



---Original---
From: "Will ***@***.***&gt;
Date: Wed, May 8, 2024 02:12 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ascendedguard/LethalCompany.ScrapLossBalancer] bug (Issue #1)




 
Closing. I wasn't able to reproduce after testing a few different ways, and haven't heard of any issues from others. Feel free to post if you're able to determine if it's a compatibility issue with another specific mod.
